name: Component Library CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: install
        run: |
          pnpm i
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
      - name: test
        run: |
          pnpm run test
